Support for OOB and Recovery code MFA challenges
auth0/Auth0.swift pull request #442
Opened 2021-01-28 06:06 UTC by ejensen

### Changes

This PR adds methods to start OOB MFA challenges and to login with OOB & recovery codes. Previously, the only supported MFA authenticator was OTP.

### References

- Support ticket https://support.auth0.com/tickets/00477858
- Addresses issue #261

### Testing

* [x] This change adds unit test coverage
* [x] This change has been tested on the latest version of the platform/language or why not

### Checklist

* [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [x] All existing and new tests complete without errors
* [ ] All active GitHub checks have passed

2021-01-29 13:17 UTC, Widcket commented
Hi @ejensen, thanks for this PR. We'll discuss this internally.

2021-01-29 13:59 UTC, Widcket commented
@ejensen can you please provide more details about your use case?

2021-01-31 20:41 UTC, ejensen commented
> @ejensen can you please provide more details about your use case?

We want to support Out Of Band (OOB) MFA Authenticators in addition to OTP MFA Authenticators. 
Auth0.Swift and Auth0.Android currently only supports OTP Authenticators. Making it impossible for users with OOB Authenticator (SMS/Voice/Email/Push) to login. Others have also reported this issue in #261

Adding API to support OOB MFA Authenticators allows clients to trigger the OOB challenges and authenticate with the responses detailed in Auth0's documentation:

- [Enroll and Challenge SMS and Voice Authenticators](https://auth0.com/docs/mfa/authenticate-with-ropg-and-mfa/enroll-challenge-sms-voice-authenticators)
- [Enroll and Challenge Email Authenticators](https://auth0.com/docs/mfa/authenticate-with-ropg-and-mfa/enroll-and-challenge-email-authenticators)
- [Enroll and Challenge Push Authenticators](https://auth0.com/docs/mfa/authenticate-with-ropg-and-mfa/enroll-and-challenge-push-authenticators)
- [Verify with out-of-band (OOB)](https://auth0.com/docs/api/authentication#verify-with-out-of-band-oob-)
- [Verify with recover code](https://auth0.com/docs/api/authentication#verify-with-recovery-code)

2021-02-01 18:37 UTC, Widcket commented
Hi @ejensen, can you please give me access to your fork so I can add a commit to see if that kickstarts the CI?

2021-02-01 18:50 UTC, ejensen commented
@Widcket The fork is public and I gave you write access

2021-02-01 19:44 UTC, Widcket commented
@ejensen I can't commit changes. We're having a CI hiccup on the iOS repos, and adding a commit fixed it for [this PR](https://github.com/auth0/JWTDecode.swift/pull/121). 

<img width="1255" alt="Screen Shot 2021-02-01 at 16 41 28" src="https://user-images.githubusercontent.com/5055789/106509456-69f8d600-64ac-11eb-9562-0b51d85a4cbe.png">

2021-02-01 19:48 UTC, Widcket commented
@ejensen Sorry, I hadn't accepted the invitation yet. My bad.

2021-02-01 22:49 UTC, Widcket requested changes
Looks good, just missing tests for `multifactorChallenge(mfaToken: String, types: [String]?, channel: String?, authenticatorId: String?)`. Make sure to test even the optional parameters.

2021-02-03 00:56 UTC, ejensen commented
@Widcket commit b0fb3b2 add tests for the `multifactorChallenge` method

2021-02-04 12:18 UTC, Widcket submitted a review, later dismissed

2021-02-04 12:34 UTC, Widcket approved these changes

2021-02-04 12:34 UTC, merged

2021-02-04 12:34 UTC, Widcket commented
Thanks @ejensen.