Add parameter option to `Request`
auth0/Auth0.swift pull request #494
Opened 2021-08-10 10:55 UTC by konDeichmann

### Changes

This PR adds the functionality to add parameters on a token-renew.

In `Request.swift` I added a function (`parameters(_ payload: [String: Any])`) that returns a copy of self.
The returned object will contain all fields from before, but with an updated payload.

The functionality is very similar to `BaseWebAuth.parameters(_:)`

This functionality is also exposed via `CredentialsManager.credentials()`.

### References

Linked to #493 

### Testing

Changes in this PR have been tested in a real-world Product. 
Unit Tests have been written to verify that `Request.parameters(_:)` work as expected.

* [x] This change adds unit test coverage
* [ ] This change has been tested on the latest version of the platform/language or why not

### Checklist

* [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [x] All existing and new tests complete without errors
* [ ] All active GitHub checks have passed

2021-08-14 01:42 UTC, Widcket commented on Auth0/CredentialsManager.swift
> +    public func credentials(withScope scope: String? = nil, minTTL: Int = 0, withParameters parameters: [String: Any] = [:], callback: @escaping (CredentialsManagerError?, Credentials?) -> Void) {
```suggestion
    public func credentials(withScope scope: String? = nil, minTTL: Int = 0, parameters: [String: Any] = [:], callback: @escaping (CredentialsManagerError?, Credentials?) -> Void) {
```

2021-08-14 01:43 UTC, Widcket commented on Auth0/CredentialsManager.swift
> +                self.retrieveCredentials(withScope: scope, minTTL: minTTL, withParameters: parameters, callback: callback)
```suggestion
                self.retrieveCredentials(withScope: scope, minTTL: minTTL, parameters: parameters, callback: callback)
```

2021-08-14 01:43 UTC, Widcket commented on Auth0/CredentialsManager.swift
> +    ///   - parameters: additional Parameter to add to a possible Token refresh, parameters will be set via Request.payload.
```suggestion
    ///   - parameters: additional parameters to add to a possible Token refresh. The parameters will be set via Request.payload.
```

2021-08-14 01:44 UTC, Widcket commented on Auth0/CredentialsManager.swift
> +            self.retrieveCredentials(withScope: scope, minTTL: minTTL, withParameters: parameters, callback: callback)
```suggestion
            self.retrieveCredentials(withScope: scope, minTTL: minTTL, parameters: parameters, callback: callback)
```

2021-08-14 01:44 UTC, Widcket commented on Auth0/CredentialsManager.swift
> +    public func credentials(withScope scope: String? = nil, minTTL: Int = 0, withParameters parameters: [String: Any] = [:], callback: @escaping (CredentialsManagerError?, Credentials?) -> Void) {
```suggestion
    public func credentials(withScope scope: String? = nil, minTTL: Int = 0, parameters: [String: Any] = [:], callback: @escaping (CredentialsManagerError?, Credentials?) -> Void) {
```

2021-08-14 01:45 UTC, Widcket commented on Auth0/CredentialsManager.swift
> +        self.retrieveCredentials(withScope: scope, minTTL: minTTL, withParameters: parameters, callback: callback)
```suggestion
        self.retrieveCredentials(withScope: scope, minTTL: minTTL, parameters: parameters, callback: callback)
```

2021-08-14 01:45 UTC, Widcket commented on Auth0/CredentialsManager.swift
> +    private func retrieveCredentials(withScope scope: String?, minTTL: Int, withParameters parameters: [String: Any] = [:], callback: @escaping (CredentialsManagerError?, Credentials?) -> Void) {
```suggestion
    private func retrieveCredentials(withScope scope: String?, minTTL: Int, parameters parameters: [String: Any] = [:], callback: @escaping (CredentialsManagerError?, Credentials?) -> Void) {
```

2021-08-14 01:46 UTC, Widcket commented on Auth0/Request.swift
> +    public func parameters(_ payload: [String: Any]) -> Self {
```suggestion
    public func parameters(_ parameters: [String: Any]) -> Self {
```

2021-08-14 01:49 UTC, Widcket commented on Auth0/Request.swift
> +     - parameter payload: Additional Parameters for the Request, provided map will be added to `paylaod`.
```suggestion
     - parameter parameters: Additional parameters for the Request. The provided map will be added to `parameters`.
```

2021-08-14 01:50 UTC, Widcket commented on Auth0/Request.swift
> +     Modify the Parameters, by creating a copy of self and adding the provided parameters to `payload`.
```suggestion
     Modify the parameters by creating a copy of self and adding the provided parameters to `parameters`.
```

2021-08-14 01:50 UTC, Widcket commented on Auth0/Request.swift
> +    public func parameters(_ payload: [String: Any]) -> Self {
```suggestion
    public func parameters(_ parameters: [String: Any]) -> Self {
```

2021-08-14 02:00 UTC, Widcket commented on Auth0/Request.swift
> +    }
```suggestion
        var mutableParameters = self.parameters
        parameters.forEach { mutableParameters[$0] = $1 }

        return Request(session: self.session, url: self.url, method: self.method, handle: self.handle, parameters: mutableParameters, headers: self.headers, logger: self.logger, telemetry: self.telemetry)
    }
```

2021-08-14 02:01 UTC, Widcket commented on Auth0Tests/AuthenticationSpec.swift
> +            }
```suggestion
            it("should contain parameters") {
                let request = auth.renew(withRefreshToken: refreshToken)

                expect(request.parameters["refresh_token"] as? String) == refreshToken
                expect(request.parameters["grant_type"] as? String) == "refresh_token"
                expect(request.parameters["client_id"] as? String) == ClientId
            }
```

2021-08-14 02:02 UTC, Widcket commented on Auth0Tests/AuthenticationSpec.swift
> +                expect(request.payload["phone"] as? String) == Phone
```suggestion
                expect(request.parameters["refresh_token"] as? String) == refreshToken
                expect(request.parameters["grant_type"] as? String) == "refresh_token"
                expect(request.parameters["client_id"] as? String) == "new Client ID"
                expect(request.parameters["phone"] as? String) == Phone
```

2021-08-14 02:02 UTC, Widcket commented on Auth0Tests/AuthenticationSpec.swift
> +                expect(baseRequest.payload as? [String: String]) == modifiedRequest.payload as? [String: String]
```suggestion
                expect(baseRequest.parameters as? [String: String]) == modifiedRequest.parameters as? [String: String]
```

2021-08-14 02:18 UTC, Widcket requested changes
Thank you for raising this PR. Looks great, just some little details.
Please add some tests in `CredentialsManagerSpec`.

2021-08-14 08:15 UTC, konDeichmann commented
Hi @Widcket, thanks for your feedback. 

I modified the Code according to your comments and added a Test that refreshes the Token with a custom parameter. The test would fail if that Parameter is not present.

I'm not too familiar with the HTTP Library therefore I don't know if my test could be improved. I'm very open for feedback again 😄

2021-08-18 03:01 UTC, Widcket commented on Auth0/CredentialsManager.swift
> +    ///   - parameters: additional parameters to add to a possible Token refresh. The parameters will be set via Request.payload.
```suggestion
    ///   - parameters: additional parameters to add to a possible token refresh. The parameters will be set via Request.payload.
```

2021-08-18 03:01 UTC, Widcket commented on Auth0Tests/CredentialsManagerSpec.swift
> +                it("Request should contain Parameter on renew") {
```suggestion
                it("Request should contain parameter on renew") {
```

2021-08-18 03:05 UTC, Widcket commented on Auth0/Request.swift
> +     - parameter payload: Additional parameters for the Request. The provided map will be added to `payload`.
```suggestion
     - parameter payload: Additional parameters for the request. The provided map will be added to `payload`.
```

2021-08-18 03:15 UTC, Widcket approved these changes
Thank you!

2021-08-18 03:17 UTC, merged

2021-09-02 21:57 UTC, Widcket commented
This is now out in version [1.36.0](https://github.com/auth0/Auth0.swift/releases/tag/1.36.0).