chore: Add privacy manifest to Auth0.Swift
auth0/Auth0.swift pull request #841
Opened 2024-04-12 11:12 UTC by poovamraj

Privacy Manifest is required by Apple from May 1st. We have added this to our SDK in this PR

- [ ] All new/changed/fixed functionality is covered by tests (or N/A)
- [x] I have added documentation for all new/changed functionality (or N/A)

### 📋 Changes

- Added PrivacyManifest file
- PrivacyManifest includes `NSPrivacyCollectedDataTypeUserID` with purpose as `NSPrivacyCollectedDataTypePurposeAppFunctionality`
- Added it to .podspec and Package.swift

### 📎 References

![Screenshot 2024-04-12 at 13 10 20](https://github.com/auth0/Auth0.swift/assets/15910425/f1c0fe91-e7b3-437c-80dc-b66d378b1573)
https://developer.apple.com/app-store/app-privacy-details/#user-tracking
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests#4144131

### 🎯 Testing

2024-04-12 12:58 UTC, Widcket commented on Auth0.podspec
> +  s.resources        = "Sources/AuthFoundation/Resources/**/*"
The path `Sources/AuthFoundation/Resources/**/*` does not exist, and as such Cocoapods cannot find the file. Did you test the changes in a sample app that uses Cocoapods?

<img width="645" alt="Screenshot 2024-04-12 at 13 55 01" src="https://github.com/auth0/Auth0.swift/assets/5055789/aec53dd4-794e-4d54-b95a-28287b320a9b">

2024-04-12 12:59 UTC, Widcket commented on Package.swift
> +            resources: [.copy(./Resources/PrivacyInfo.xcprivacy)]
The syntax is invalid and does not compile. Did you test the changes on a sample app that uses the Swift Package Manager?

<img width="803" alt="Screenshot 2024-04-12 at 13 54 37" src="https://github.com/auth0/Auth0.swift/assets/5055789/6f273b53-0846-4755-a92a-cf76f61171c0">

2024-04-12 13:14 UTC, Widcket commented on Resources/PrivacyInfo.xcprivacy
> +			<string>NSPrivacyCollectedDataTypeUserID</string>
This is missing `NSPrivacyCollectedDataTypeTracking` (`false`), and `NSPrivacyCollectedDataTypeLinked` (`true`).
Did you verify that the PDF privacy report gets generated with the correct content from an app archive?

2024-04-12 13:15 UTC, Widcket requested changes
This is missing the changes needed to support apps that use Carthage to install Auth0.swift.
Did you test the changes in a sample app that uses Carthage?

2024-04-12 17:47 UTC, Widcket approved these changes

2024-04-12 17:54 UTC, merged

2024-05-03 15:46 UTC, wongk commented
This change is causing an error when building our application.
```
error: Multiple commands produce '/Users/expo/Library/Developer/Xcode/DerivedData/HealthCoach-cadkgkgehnezpjdtijikapiciihy/Build/Intermediates.noindex/ArchiveIntermediates/HealthCoach/InstallationBuildProductsLocation/Applications/HealthCoach.app/PrivacyInfo.xcprivacy'
```

Please see: https://stackoverflow.com/a/78344724. The podspec should use the following format:
```
"resource_bundles": {"LibName": "LibName/PrivacyInfo.xcprivacy"}
```